name: malaria_report_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  http: ^1.3.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist.ttf
  assets:
    - assets/images/logo.png
      
