class Malaria {
  int? id;
  String reporter_id;
  String reporter_name;
  String reporter_township;
  String reporter_village;
  String volunteer_id;
  String volunteer_name;
  String volunteer_township;
  String volunteer_village;
  String treatment_month;
  String treatment_year;
  String test_date;
  String patient_name;
  String age_unit;
  String age;
  String address;
  String sex;
  String isPregnant;
  String lact_mother;
  String rdtResult;
  String malariaParasite;
  String symptoms;
  String act24;
  String act24_amount;
  String act18;
  String act18_amount;
  String act12;
  String act12_amount;
  String act6;
  String act6_amount;
  String cq;
  String cq_amount;
  String pq;
  String pq_amount;
  String isReferred;
  String isDead;
  String receivedTreatment;
  String travelling_before;
  String occupation;
  String persons_with_disability;
  String internally_displaced;
  String remark;
  String syncStatus;

  Malaria({
    this.id,
    required this.reporter_id,
    required this.reporter_name,
    required this.reporter_township,
    required this.reporter_village,
    required this.volunteer_id,
    required this.volunteer_name,
    required this.volunteer_township,
    required this.volunteer_village,
    required this.treatment_month,
    required this.treatment_year,
    required this.test_date,
    required this.patient_name,
    required this.age_unit,
    required this.age,
    required this.address,
    required this.sex,
    required this.isPregnant,
    required this.lact_mother,
    required this.rdtResult,
    required this.malariaParasite,
    required this.symptoms,
    required this.act24,
    required this.act24_amount,
    required this.act18,
    required this.act18_amount,
    required this.act12,
    required this.act12_amount,
    required this.act6,
    required this.act6_amount,
    required this.cq,
    required this.cq_amount,
    required this.pq,
    required this.pq_amount,
    required this.isReferred,
    required this.isDead,
    required this.receivedTreatment,
    required this.travelling_before,
    required this.occupation,
    required this.persons_with_disability,
    required this.internally_displaced,
    required this.remark,
    required this.syncStatus,
  });
}
