class Malaria {
  int? id;
  String dataCollectorId;
  String dataCollectorName;
  String dataCollectorTownship;
  String dataCollectorVillage;
  String volunteerId;
  String volunteerName;
  String volunteerTownship;
  String volunteerVillage;
  String tMonth;
  String tYear;
  String dateOfRdt;
  String patientName;
  String ageUnit;
  String patientAge;
  String patientAddress;
  String patientSex;
  String isPregnant;
  String isLactatingMother;
  String rdtResult;
  String malariaParasite;
  String symptoms;
  String act24;
  String act24Count;
  String act18;
  String act18Count;
  String act12;
  String act12Count;
  String act6;
  String act6Count;
  String chloroquine;
  String chloroquineCount;
  String primaquine;
  String primaquineCount;
  String isReferred;
  String isDead;
  String receivedTreatment;
  String hasTravelled;
  String occupation;
  String isPersonWithDisabilities;
  String isInternallyDisplaced;
  String remark;
  String syncStatus;

  Malaria({
    this.id,
    required this.dataCollectorId,
    required this.dataCollectorName,
    required this.dataCollectorTownship,
    required this.dataCollectorVillage,
    required this.volunteerId,
    required this.volunteerName,
    required this.volunteerTownship,
    required this.volunteerVillage,
    required this.tMonth,
    required this.tYear,
    required this.dateOfRdt,
    required this.patientName,
    required this.ageUnit,
    required this.patientAge,
    required this.patientAddress,
    required this.patientSex,
    required this.isPregnant,
    required this.isLactatingMother,
    required this.rdtResult,
    required this.malariaParasite,
    required this.symptoms,
    required this.act24,
    required this.act24Count,
    required this.act18,
    required this.act18Count,
    required this.act12,
    required this.act12Count,
    required this.act6,
    required this.act6Count,
    required this.chloroquine,
    required this.chloroquineCount,
    required this.primaquine,
    required this.primaquineCount,
    required this.isReferred,
    required this.isDead,
    required this.receivedTreatment,
    required this.hasTravelled,
    required this.occupation,
    required this.isPersonWithDisabilities,
    required this.isInternallyDisplaced,
    required this.remark,
    required this.syncStatus,
  });
}
